// Mocks generated by Mockito 5.4.4 from annotations
// in docdiscovery/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i10;

import 'package:algolia/algolia.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:docdiscovery/core/error/failure.dart' as _i8;
import 'package:docdiscovery/domain/entities/practitioner.dart' as _i9;
import 'package:docdiscovery/domain/repositories/practitioner_repository.dart'
    as _i4;
import 'package:docdiscovery/domain/usecases/get_practitioner_info_use_case.dart'
    as _i13;
import 'package:docdiscovery/domain/usecases/get_practitioner_profile_use_case.dart'
    as _i18;
import 'package:docdiscovery/domain/usecases/save_practitioner_use_case.dart'
    as _i12;
import 'package:docdiscovery/domain/usecases/search_practitioner_use_case.dart'
    as _i14;
import 'package:file_picker/src/file_picker.dart' as _i16;
import 'package:file_picker/src/file_picker_result.dart' as _i17;
import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:firebase_storage/firebase_storage.dart' as _i6;
import 'package:flutter/src/widgets/navigator.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlgolia_1 extends _i1.SmartFake implements _i3.Algolia {
  _FakeAlgolia_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlgoliaMultiIndexesReference_2 extends _i1.SmartFake
    implements _i3.AlgoliaMultiIndexesReference {
  _FakeAlgoliaMultiIndexesReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlgoliaIndexReference_3 extends _i1.SmartFake
    implements _i3.AlgoliaIndexReference {
  _FakeAlgoliaIndexReference_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlgoliaIndexesSnapshot_4 extends _i1.SmartFake
    implements _i3.AlgoliaIndexesSnapshot {
  _FakeAlgoliaIndexesSnapshot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePractitionerRepository_5 extends _i1.SmartFake
    implements _i4.PractitionerRepository {
  _FakePractitionerRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseApp_6 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_7 extends _i1.SmartFake implements Duration {
  _FakeDuration_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReference_8 extends _i1.SmartFake implements _i6.Reference {
  _FakeReference_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PractitionerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPractitionerRepository extends _i1.Mock
    implements _i4.PractitionerRepository {
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>> savePractitioner(
          _i9.PractitionerEntity? practitioner) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePractitioner,
          [practitioner],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #savePractitioner,
            [practitioner],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #savePractitioner,
            [practitioner],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>> getById(
          String? practitionerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [practitionerId],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #getById,
            [practitionerId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #getById,
            [practitionerId],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>);

  @override
  _i7.Future<List<_i9.PractitionerEntity>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i7.Future<List<_i9.PractitionerEntity>>.value(
            <_i9.PractitionerEntity>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i9.PractitionerEntity>>.value(
                <_i9.PractitionerEntity>[]),
      ) as _i7.Future<List<_i9.PractitionerEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> uploadPractitionerProfile(
    String? practitionerId,
    _i10.Uint8List? profile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPractitionerProfile,
          [
            practitionerId,
            profile,
          ],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #uploadPractitionerProfile,
            [
              practitionerId,
              profile,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, String>>.value(
                _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #uploadPractitionerProfile,
            [
              practitionerId,
              profile,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> getProfile(
          String? practitionerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [practitionerId],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #getProfile,
            [practitionerId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, String>>.value(
                _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #getProfile,
            [practitionerId],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);
}

/// A class which mocks [Algolia].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlgolia extends _i1.Mock implements _i3.Algolia {
  @override
  String get applicationId => (super.noSuchMethod(
        Invocation.getter(#applicationId),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#applicationId),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#applicationId),
        ),
      ) as String);

  @override
  Map<String, String> get extraHeaders => (super.noSuchMethod(
        Invocation.getter(#extraHeaders),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  List<String> get extraUserAgents => (super.noSuchMethod(
        Invocation.getter(#extraUserAgents),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i3.Algolia get instance => (super.noSuchMethod(
        Invocation.getter(#instance),
        returnValue: _FakeAlgolia_1(
          this,
          Invocation.getter(#instance),
        ),
        returnValueForMissingStub: _FakeAlgolia_1(
          this,
          Invocation.getter(#instance),
        ),
      ) as _i3.Algolia);

  @override
  _i3.AlgoliaMultiIndexesReference get multipleQueries => (super.noSuchMethod(
        Invocation.getter(#multipleQueries),
        returnValue: _FakeAlgoliaMultiIndexesReference_2(
          this,
          Invocation.getter(#multipleQueries),
        ),
        returnValueForMissingStub: _FakeAlgoliaMultiIndexesReference_2(
          this,
          Invocation.getter(#multipleQueries),
        ),
      ) as _i3.AlgoliaMultiIndexesReference);

  @override
  _i3.Algolia setHeader(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHeader,
          [
            key,
            value,
          ],
        ),
        returnValue: _FakeAlgolia_1(
          this,
          Invocation.method(
            #setHeader,
            [
              key,
              value,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeAlgolia_1(
          this,
          Invocation.method(
            #setHeader,
            [
              key,
              value,
            ],
          ),
        ),
      ) as _i3.Algolia);

  @override
  _i3.AlgoliaIndexReference index(String? index) => (super.noSuchMethod(
        Invocation.method(
          #index,
          [index],
        ),
        returnValue: _FakeAlgoliaIndexReference_3(
          this,
          Invocation.method(
            #index,
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeAlgoliaIndexReference_3(
          this,
          Invocation.method(
            #index,
            [index],
          ),
        ),
      ) as _i3.AlgoliaIndexReference);

  @override
  _i7.Future<_i3.AlgoliaIndexesSnapshot> getIndices() => (super.noSuchMethod(
        Invocation.method(
          #getIndices,
          [],
        ),
        returnValue: _i7.Future<_i3.AlgoliaIndexesSnapshot>.value(
            _FakeAlgoliaIndexesSnapshot_4(
          this,
          Invocation.method(
            #getIndices,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.AlgoliaIndexesSnapshot>.value(
            _FakeAlgoliaIndexesSnapshot_4(
          this,
          Invocation.method(
            #getIndices,
            [],
          ),
        )),
      ) as _i7.Future<_i3.AlgoliaIndexesSnapshot>);

  @override
  _i7.Future<void> pushEvents(List<_i3.AlgoliaEvent>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushEvents,
          [events],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SavePractitionerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavePractitionerUseCase extends _i1.Mock
    implements _i12.SavePractitionerUseCase {
  @override
  _i4.PractitionerRepository get practitionerRepository => (super.noSuchMethod(
        Invocation.getter(#practitionerRepository),
        returnValue: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
        returnValueForMissingStub: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
      ) as _i4.PractitionerRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>> execute(
          _i9.PractitionerEntity? practitioner) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [practitioner],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #execute,
            [practitioner],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #execute,
            [practitioner],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>);
}

/// A class which mocks [GetPractitionerInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPractitionerInfoUseCase extends _i1.Mock
    implements _i13.GetPractitionerInfoUseCase {
  @override
  _i4.PractitionerRepository get practitionerRepository => (super.noSuchMethod(
        Invocation.getter(#practitionerRepository),
        returnValue: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
        returnValueForMissingStub: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
      ) as _i4.PractitionerRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>> execute(
          String? practitionerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [practitionerId],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #execute,
            [practitionerId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>.value(
                _FakeEither_0<_i8.Failure, _i9.PractitionerEntity>(
          this,
          Invocation.method(
            #execute,
            [practitionerId],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i9.PractitionerEntity>>);
}

/// A class which mocks [SearchPractitionerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPractitionerUseCase extends _i1.Mock
    implements _i14.SearchPractitionerUseCase {
  @override
  _i4.PractitionerRepository get practitionerRepository => (super.noSuchMethod(
        Invocation.getter(#practitionerRepository),
        returnValue: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
        returnValueForMissingStub: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
      ) as _i4.PractitionerRepository);

  @override
  _i7.Future<List<_i9.PractitionerEntity>> execute(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [query],
        ),
        returnValue: _i7.Future<List<_i9.PractitionerEntity>>.value(
            <_i9.PractitionerEntity>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i9.PractitionerEntity>>.value(
                <_i9.PractitionerEntity>[]),
      ) as _i7.Future<List<_i9.PractitionerEntity>>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i15.NavigatorObserver {
  @override
  void didPush(
    _i15.Route<dynamic>? route,
    _i15.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i15.Route<dynamic>? route,
    _i15.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i15.Route<dynamic>? route,
    _i15.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i15.Route<dynamic>? newRoute,
    _i15.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i15.Route<dynamic>? route,
    _i15.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FilePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePicker extends _i1.Mock implements _i16.FilePicker {
  @override
  _i7.Future<_i17.FilePickerResult?> pickFiles({
    String? dialogTitle,
    String? initialDirectory,
    _i16.FileType? type = _i16.FileType.any,
    List<String>? allowedExtensions,
    dynamic Function(_i16.FilePickerStatus)? onFileLoading,
    bool? allowCompression = true,
    bool? allowMultiple = false,
    bool? withData = false,
    bool? withReadStream = false,
    bool? lockParentWindow = false,
    bool? readSequential = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickFiles,
          [],
          {
            #dialogTitle: dialogTitle,
            #initialDirectory: initialDirectory,
            #type: type,
            #allowedExtensions: allowedExtensions,
            #onFileLoading: onFileLoading,
            #allowCompression: allowCompression,
            #allowMultiple: allowMultiple,
            #withData: withData,
            #withReadStream: withReadStream,
            #lockParentWindow: lockParentWindow,
            #readSequential: readSequential,
          },
        ),
        returnValue: _i7.Future<_i17.FilePickerResult?>.value(),
        returnValueForMissingStub: _i7.Future<_i17.FilePickerResult?>.value(),
      ) as _i7.Future<_i17.FilePickerResult?>);

  @override
  _i7.Future<bool?> clearTemporaryFiles() => (super.noSuchMethod(
        Invocation.method(
          #clearTemporaryFiles,
          [],
        ),
        returnValue: _i7.Future<bool?>.value(),
        returnValueForMissingStub: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);

  @override
  _i7.Future<String?> getDirectoryPath({
    String? dialogTitle,
    bool? lockParentWindow = false,
    String? initialDirectory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectoryPath,
          [],
          {
            #dialogTitle: dialogTitle,
            #lockParentWindow: lockParentWindow,
            #initialDirectory: initialDirectory,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> saveFile({
    String? dialogTitle,
    String? fileName,
    String? initialDirectory,
    _i16.FileType? type = _i16.FileType.any,
    List<String>? allowedExtensions,
    bool? lockParentWindow = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFile,
          [],
          {
            #dialogTitle: dialogTitle,
            #fileName: fileName,
            #initialDirectory: initialDirectory,
            #type: type,
            #allowedExtensions: allowedExtensions,
            #lockParentWindow: lockParentWindow,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);
}

/// A class which mocks [FirebaseStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorage extends _i1.Mock implements _i6.FirebaseStorage {
  @override
  _i5.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_6(
          this,
          Invocation.getter(#app),
        ),
        returnValueForMissingStub: _FakeFirebaseApp_6(
          this,
          Invocation.getter(#app),
        ),
      ) as _i5.FirebaseApp);

  @override
  set app(_i5.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get bucket => (super.noSuchMethod(
        Invocation.getter(#bucket),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#bucket),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#bucket),
        ),
      ) as String);

  @override
  set bucket(String? _bucket) => super.noSuchMethod(
        Invocation.setter(
          #bucket,
          _bucket,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration get maxOperationRetryTime => (super.noSuchMethod(
        Invocation.getter(#maxOperationRetryTime),
        returnValue: _FakeDuration_7(
          this,
          Invocation.getter(#maxOperationRetryTime),
        ),
        returnValueForMissingStub: _FakeDuration_7(
          this,
          Invocation.getter(#maxOperationRetryTime),
        ),
      ) as Duration);

  @override
  Duration get maxUploadRetryTime => (super.noSuchMethod(
        Invocation.getter(#maxUploadRetryTime),
        returnValue: _FakeDuration_7(
          this,
          Invocation.getter(#maxUploadRetryTime),
        ),
        returnValueForMissingStub: _FakeDuration_7(
          this,
          Invocation.getter(#maxUploadRetryTime),
        ),
      ) as Duration);

  @override
  Duration get maxDownloadRetryTime => (super.noSuchMethod(
        Invocation.getter(#maxDownloadRetryTime),
        returnValue: _FakeDuration_7(
          this,
          Invocation.getter(#maxDownloadRetryTime),
        ),
        returnValueForMissingStub: _FakeDuration_7(
          this,
          Invocation.getter(#maxDownloadRetryTime),
        ),
      ) as Duration);

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i6.Reference ref([String? path]) => (super.noSuchMethod(
        Invocation.method(
          #ref,
          [path],
        ),
        returnValue: _FakeReference_8(
          this,
          Invocation.method(
            #ref,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeReference_8(
          this,
          Invocation.method(
            #ref,
            [path],
          ),
        ),
      ) as _i6.Reference);

  @override
  _i6.Reference refFromURL(String? url) => (super.noSuchMethod(
        Invocation.method(
          #refFromURL,
          [url],
        ),
        returnValue: _FakeReference_8(
          this,
          Invocation.method(
            #refFromURL,
            [url],
          ),
        ),
        returnValueForMissingStub: _FakeReference_8(
          this,
          Invocation.method(
            #refFromURL,
            [url],
          ),
        ),
      ) as _i6.Reference);

  @override
  void setMaxOperationRetryTime(Duration? time) => super.noSuchMethod(
        Invocation.method(
          #setMaxOperationRetryTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxUploadRetryTime(Duration? time) => super.noSuchMethod(
        Invocation.method(
          #setMaxUploadRetryTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxDownloadRetryTime(Duration? time) => super.noSuchMethod(
        Invocation.method(
          #setMaxDownloadRetryTime,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> useEmulator({
    required String? host,
    required int? port,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #useEmulator,
          [],
          {
            #host: host,
            #port: port,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> useStorageEmulator(
    String? host,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #useStorageEmulator,
          [
            host,
            port,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [GetPractitionerProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPractitionerProfileUseCase extends _i1.Mock
    implements _i18.GetPractitionerProfileUseCase {
  @override
  _i4.PractitionerRepository get practitionerRepository => (super.noSuchMethod(
        Invocation.getter(#practitionerRepository),
        returnValue: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
        returnValueForMissingStub: _FakePractitionerRepository_5(
          this,
          Invocation.getter(#practitionerRepository),
        ),
      ) as _i4.PractitionerRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> execute(String? practitionerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [practitionerId],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [practitionerId],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Either<_i8.Failure, String>>.value(
                _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [practitionerId],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);
}
